name: pr_verification # ì›Œí¬ í”Œë¡œìš° ì´ë¦„

on: # ì›Œí¬ í”Œë¡œìš° ì‹¤í–‰ íŠ¸ë¦¬ê±°
  pull_request: # PRì´ ì‹¤í–‰ë  ë•Œ
    types: [opened, synchronize] # PRì´ ì—´ë ¸ì„ ë•Œ, ì—…ë°ì´íŠ¸ ëì„ ë•Œ

jobs: # ì‘ì—… ì •ì˜
  check:
    runs-on: ubuntu-lastest # ìš°ë¶„íˆ¬ í™˜ê²½
    permissions: #ê¶Œí•œ ì„¤ì •
      pull-requests: write # PR ì“°ê¸° ê¶Œí•œ ì„¤ì •
    steps: # ì‹¤ì œë¡œ ì‹¤í–‰ë˜ëŠ” ì‘ì—… ë‹¨ê³„
      - uses: actions/github-script@v7
        with:
          script: | # ìŠ¤í¬ë¦½íŠ¸ ì‹œì‘
            const pull_requst = context.payload.pull_request; #pull_request ê°ì²´ ê°€ì ¸ì˜¤ê¸°

            if (pull_requst === undefined) {  # pull_requstê°€ ì—†ëŠ” ê²½ìš°
              console.log("The corresponding PR cannot be verified.")
              return;
            }

            const pr_body = pull_requst.body;

            if(!pr_body) { //PR ë‚´ìš©ì´ ë¹„ì–´ ìˆë‹¤ë©´
                //PRì— ì½”ë©˜íŠ¸ ì¶”ê°€
                await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pull_requst.number,
                    body: "í•´ë‹¹ pull requestëŠ” ê°€ì´ë“œë¼ì¸ì„ ì¤€ìˆ˜í•˜ì§€ ì•Šì•„ close ì²˜ë¦¬ê°€ ë˜ì—ˆìŠµë‹ˆë‹¤. ê°€ì´ë“œë¼ì¸ì„ ì¤€ìˆ˜í•´ì„œ ë‹¤ì‹œ pull requestë¥¼ ìš”ì²­í•´ì£¼ì„¸ìš”.ğŸ˜‰"  
                })

                //í•´ë‹¹ PRì„ ë‹«ìŠµë‹ˆë‹¤.
                await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pull_requst.number,
                    state: close
                })
            }
